# Generated by Django 4.0.1 on 2022-07-19 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carosule',
        ),
    ]
