# Generated by Django 4.0.1 on 2022-07-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0005_product_alter_carousel_button_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
