# Generated by Django 4.0.1 on 2022-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_description', models.TextField(max_length=300)),
                ('reviews', models.IntegerField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
