# Generated by Django 4.0.1 on 2022-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.CharField(max_length=5),
        ),
    ]
