# Generated by Django 4.0.6 on 2022-07-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
