# Generated by Django 4.0.6 on 2022-07-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
