# Generated by Django 4.0.6 on 2022-07-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0012_rename_contact_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=250)),
                ('Stock_Group', models.CharField(blank=True, max_length=250, null=True)),
                ('Stock_Category', models.CharField(blank=True, max_length=250, null=True)),
                ('Base_Unit_Qty', models.FloatField(blank=True, null=True)),
                ('Rate', models.FloatField(blank=True, null=True)),
                ('GST_Applicable', models.CharField(default='True', max_length=100)),
                ('HSN_SAC_Code', models.CharField(blank=True, max_length=250, null=True)),
                ('IGST_Rate', models.IntegerField(blank=True, null=True)),
                ('Reporting_UQC', models.CharField(blank=True, max_length=250, null=True)),
                ('MRP_Rate', models.FloatField(blank=True, null=True)),
                ('Manufracturing_Date', models.CharField(blank=True, max_length=250, null=True)),
                ('Image_Link', models.TextField(blank=True, max_length=15000, null=True)),
            ],
        ),
    ]
