# Generated by Django 4.0.6 on 2022-07-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeJMT', '0015_about_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='desciption',
            new_name='description',
        ),
    ]
